name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get install plantuml verilator direnv
        brew install uv

    - name: Build and sim
      run: |
        direnv add .
        cd example
        direnv exec ../ make

